name = "OnlineStatsChainsVizExamples"
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"

[compat]
Colors = "0.12, 0.13"
JSServe = "2"
JSON3 = "1"
OnlineStats = "1"
julia = "1.10"

# Note: OnlineStatsChains should be dev'd from parent directory
# Run in this directory: using Pkg; Pkg.develop(path="../..")
