name = "OnlineStatsChains"
uuid = "c3092dcd-a09e-45f3-b86d-18109bff285f"
authors = ["FemtoTrader <femto.trader@gmail.com>"]
version = "0.3.0"

[deps]
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"

[compat]
Documenter = "1"
OnlineStats = "1"
OnlineStatsBase = "1"
Rocket = "1.8"
Test = "1"
TestItemRunner = "1"
julia = "1.10"

[weakdeps]
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"

[extensions]
OnlineStatsChainsRocketExt = "Rocket"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "OnlineStats", "TestItemRunner"]
