name = "OnlineStatsChainsReactiveExamples"
version = "0.1.0"

[deps]
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"

[compat]
OnlineStats = "1"
Rocket = "1.8"
julia = "1.10"

# Note: OnlineStatsChains should be dev'd from parent directory
# Run in this directory: using Pkg; Pkg.develop(path="../..")
