name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'    # Latest stable release
          - '1.11'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        include:
          # Add nightly on Linux (allowed to fail)
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v1
        with:
          cache-name: ${{ runner.os }}-test

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
        continue-on-error: ${{ matrix.version == 'nightly' }}

      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest'

      - uses: codecov/codecov-action@v4
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  test-rocket:
    name: Julia ${{ matrix.version }} - Rocket.jl integration - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'    # LTS
          - '1'       # Latest stable
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v1
        with:
          cache-name: ${{ runner.os }}-test-rocket

      - name: Install OnlineStatsChains dependencies
        run: |
          julia --project -e '
            using Pkg
            Pkg.instantiate()
          '

      - name: Install Rocket.jl
        run: |
          julia --project -e '
            using Pkg
            Pkg.add("Rocket")
          '

      - name: Run Rocket.jl integration tests
        run: |
          julia --project -e '
            using Pkg
            Pkg.test()
          '
